### ISSUE TITLE
How to use the dedicated EU base URL

### ISSUE THREAD

**Issue by hqiu-at-wiris** [ipregistry/ipregistry-python#39]
We have seen in a recent update that you are introducing a dedicated EU base URL. Will you modify the library to be able to use this endpoint?

**Comment by lpellegr** [comment]
Good question. You can already configure the Ipregistry client to use the new base URL as follows:

```python
from ipregistry import IpregistryClient, IpregistryConfig
client = IpregistryClient(IpregistryConfig("tryout", "https://eu.api.ipregistry.co"))
```

We will update the documentation and probably introduce a new parameter in the IpregistryClient constructor to simplify the usage (i.e. avoid creating an instance of IpregistryConfig) but the method presented above will continue to work.

**Comment by hqiu-at-wiris** [comment]
Thank you for such a quick response! We have already tried it and it works fine for us.
